name: Deploying Prod Branch

on:
  push:
    branches:
      - Prod
jobs:
  deploy:

    runs-on: [self-hosted, certiqas-backend-vm]

    env:
      PM2_PROCESS_NAME: certiqas-backend-Prod
      NODE_VERSION: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: False
          path: Prod-Branch

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: Prod-Branch

      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            pm2 start "npm start" --name "$PM2_PROCESS_NAME"
          fi
        working-directory: Prod-Branch
