name: Deploying stg Branch

on:
  push:
    branches:
      - Stg

jobs:
  build:
    runs-on: [self-hosted,certiqas-backend-vm]

    env:
      PM2_PROCESS_NAME: certiqas-backend-Stg
      node-version: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            pm2 start "npm start" --name "$PM2_PROCESS_NAME"
          fi
          pm2 save
